site_name: Lexie's Note
site_url: https://slowist-lee.github.io/notebook/
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font: false
    # code: JetBrains Mono
  # icon:
    # logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
repo_url: https://github.com/lexie-423/notebook-by-zizi
repo_name: Lexie's Notebook
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lexie-423
    - icon: fontawesome/regular/envelope
      link: mushroomzizi@outlook.com

  feedback:
    title: 此页面有帮助吗？
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          谢谢你的反馈！
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! 

plugins:
  - mermaid2: {}
  - search
  - callouts
  - encryptcontent:
      title_prefix: '🔒'
      summary: '请输入密码查看.'
      encryption_info_message: '此内容已加密, 请输入密码查看.'
      decryption_failure_message: '密码错误, 如有需要，请联系Lexie.'
      hljs: False
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - statistics
  - changelog
  - git-revision-date-localized:
      enable_creation_date: true 
  - toc
markdown_extensions:
  - attr_list
  - md_in_html
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list



  # - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight: # 代码块高亮
      auto_title: false # 显示编程语言名称
extra_javascript:
  - js/katex.js
  - js/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; 2025 Lexie Yu/All Rights Reserved. # 左下角的版权声明

nav:
  - Home:
    - index.md
    - 更新记录: changelog.md
    - 笔记目录: Content.md
    - To Do List: Writings/essay/22.md
  - SP:
    - SP/index.md
    - 深度学习: 
      - AI/DL/index.md
      - 1. Pytorch 基础使用: AI/DL/1.md
      - 2.自动微分的Pytorch实现: AI/DL/2.md
    - 机器学习:
      - AI/ML/index.md
      - 0. 机器学习概述: AI/ML/0.md
      - 1. 统计学习&监督学习概论: AI/ML/1.md
      - 2. 感知机: AI/ML/2.md
      - 3. SVM算法: AI/ML/3.md
    - 其他知识:
      - AI/Others/index.md
      - 1. 搜索: AI/Others/Search.md
  - Math: 
    - Math/index.md
    - 抽样调查:
      - 简单随机抽样: Math/sampling suevey/simple random samling.md
    - 高等数学（微积分）:
      - 极限计算: Math/Math1/limit.md
    - 复变函数与积分变换: Math/complex/index.md
    - 概率论与数理统计: Math/Probability/Error.md
    - 数学建模: 
      - Math/MathModel/index.md
      - 1. 数学规划: Math/MathModel/program/program.md
      - 2. 图论模型: Math/MathModel/graph/graph.md
      - 3. 组合优化: Math/MathModel/combination-optimize/note.md
      - 4. 习题笔记: Math/MathModel/exercise/index.md
      - 5. Review: Math/MathModel/review/note.md
      - 6. Test:
        - 24-25秋冬期末(ACEE): Math/MathModel/test/index.md
  - Gallery:
    - 写在开头: photo/index.md
    - Film 菲林卷:
      - 叁: photo/Kodakfilm3/kodak3.md
    - 观鸟日记:
        - 2602 定海湿地公园&叉河水库: docs/All_about_birds/2602/wetland_reservoir/wetland$reservoir2602.md
  - Writings:
    - 写在开头: Writing/index.md
    - 古典乐评: 
      - Writing/Classical/intro.md
      - 谢尔盖·拉赫玛尼诺夫: Writing/Classical/Rach/about-rach.md
      - 帕格尼尼主题狂想曲 : Writing/Classical/Rach/Pag.md
